#!/bin/bash -l
#
#Number of cores requested
#$ -pe omp 16
#Give the name to the job
#$ -N kraken_blast_2v2
#Send an email when the job is finished (or aborted)
#$ -m ae
#Join the error and output file
#$ -j y
# Set the runtime limit (default 12 hours):
#$ -l h_rt=12:00:00
# Specify your project
#$ -P ct-shbioinf
module load blast+
module load R/3.6.2 #load R3.6.2
module load sratoolkit
cd /projectnb/ct-shbioinf/vrapela/Kraken2_compare
DBNAME=kdb
mkdir $DBNAME
kraken/kraken2-build --download-taxonomy --db $DBNAME
kraken/kraken2-build --download-library nt --threads 12 --db $DBNAME
Rscript 'Code/kraken-blast-matk2.R' #run the script
